### ISSUE TITLE
Generic question about API usage

### ISSUE THREAD

**Issue by eveningkid** [XHMM/react-native-cloud-store#27]
Hello,

First off, thank you so much for making this a bliss to install through Expo and for maintaining this library for so long!

I am using `AsyncStorage` at the moment to store everything locally and would want to store these on iCloud.

The key-value store size is too small to contain all of the data I have, so I thought of using iCloud containers through your library.

A few questions:
1. Is the data stored in iCloud user-scoped? As in, only that user gets access to it through their Apple ID? Or is it shared?
I ask because I read that CloudKit (which from my understanding is not what we're using here) has different levels of privacy, and [that line in the Expo plugin](https://github.com/XHMM/react-native-cloud-store/blob/main/plugins/withCloud.js#L57C11-L57C53) made me wonder if all data was public?
```js
NSUbiquitousContainerIsDocumentScopePublic: true,
```
2. I got confused by the mention of local paths. Does it mean that you can have both local and iCloud on your device using this library?
3. If so, given my data is already stored in `AsyncStorage`, what is the right chain of actions to store that data on iCloud?
Do I need to use `writeFile`, `upload`, or `setUbiquitous`? If you don't mind giving a code example, that would be really helpful.
4. Same question for `readFile`: do we need to first check locally if an iCloud file is downloaded, call `download`otherwise, then only you can `readFile`, or is this wrong?

Thanks in advance for your help, it would really be appreciated!

**Comment by XHMM** [comment]
Glad to help you！

1. Data sotred in iCloud container is associated with your  apple account, CloudKit is just like a Baas, so the two are different things.  Setting NSUbiquitousContainerIsDocumentScopePublic to true means the folder will be visible to user so user can modify files directly without through your app.
2. Local path means the path from your application (I will update the doc with a more clear explanation).  Why I emphasize the two paths? Because the path of iCloud container and path of your app are different things although they are both the path, passed wrong path would lead to unexpected behavior which made you annoying to debug.
3. Data exists as files in iCloud, so you should need to write a migrating step to convert your AsyncStorage data to files. You can store them as a json file or use some offline database such as watermelon db, realm. The latter is more complex because you need to handle data sync between your application and iCloud container manually. (I wrote [an article](https://medium.com/@xhmm/how-to-backup-realm-database-to-icloud-using-reactnative-9fd038a0a6b1) before you can check )
4. You cannot read the file if it not downloaded. You can check if it exists, if not, download it and readn or just read.

**Comment by eveningkid** [comment]
@XHMM this has been very useful, thank you!

Your library has been a life saver, given everybody else's library only gives access to the key/value store.

Have a great rest of your week, thanks again!

**Comment by hammadresourcifi** [comment]
@XHMM @eveningkid I am confused. Can we upload the data in user's personal icloud or not? Really appreciate any help

**Comment by XHMM** [comment]
> @XHMM @eveningkid I am confused. Can we upload the data in user's personal icloud or not? Really appreciate any help

Your app can only handler the iCloud data created by you(identifiers specified in your XCode capabilities), you can not visit the data from other places for example the root Documents folder

**Comment by bumpingChris** [comment]
@XHMM @eveningkid 
Thank you @XHMM for maintaining this library! 
I'm new to iCloud syncing, and so have a few basic understanding questions. I hope you can help clarify them for me.
Is my understanding on the following correct?

1. On the mobile device, there are two locations where files are/can be stored:  
    1) Local path = app relative path (e.g. /var/mobile/Containers/Data/Application/1A6CCFDA-89DC-4FE7-8CF0-72180FD34FBB/Documents/my.db). 
    2) Cloud container path = directory where files are synced to the cloud. (e.g. /private/var/mobile/Library/Mobile Documents/iCloud~com~project~app/Documents/my.db). **Files here exist locally AND remotely?**

2. When we execute a method like CloudStore.download, we're getting the latest version of the file from the remote cloud container to the local cloud container? And, once downloaded, we need to use RNFS.copyFile to copy the file from the cloud container to a app-relative location (e.g. RNFS.copyFile(/private/var/mobile/Library/Mobile Documents/iCloud~com~project~app/Documents/my.db, /var/mobile/Containers/Data/Application/1A6CCFDA-89DC-4FE7-8CF0-72180FD34FBB/Documents/my.db)? 

3. What's the difference between CloudStore.download and CloudStore.startDownloadingUbiquitousItem ?

Thank you in advance for your help in all this!
